// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Nexit.Infrastructure.Data;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Nexit.Infrastructure.Migrations
{
    [DbContext(typeof(NexitDbContext))]
    [Migration("20260910012649_AddClienteYProyectoAdjuntos")]
    partial class AddClienteYProyectoAdjuntos
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Nexit.Core.Entities.CategoriaProveedor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("nombre");

                    b.HasKey("Id")
                        .HasName("pk_categorias_proveedor");

                    b.HasIndex("Nombre")
                        .IsUnique()
                        .HasDatabaseName("ix_categorias_proveedor_nombre");

                    b.ToTable("categorias_proveedor", (string)null);
                });

            modelBuilder.Entity("Nexit.Core.Entities.Ciudad", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("nombre");

                    b.Property<Guid>("RegionId")
                        .HasColumnType("uuid")
                        .HasColumnName("region_id");

                    b.HasKey("Id")
                        .HasName("pk_ciudades");

                    b.HasIndex("RegionId", "Nombre")
                        .IsUnique()
                        .HasDatabaseName("ix_ciudades_region_id_nombre");

                    b.ToTable("ciudades", (string)null);
                });

            modelBuilder.Entity("Nexit.Core.Entities.Cliente", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("CargoContacto")
                        .HasColumnType("text")
                        .HasColumnName("cargo_contacto");

                    b.Property<string>("Ciudad")
                        .HasColumnType("text")
                        .HasColumnName("ciudad");

                    b.Property<Guid?>("CiudadId")
                        .HasColumnType("uuid")
                        .HasColumnName("ciudad_id");

                    b.Property<string>("Contacto")
                        .HasColumnType("text")
                        .HasColumnName("contacto");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("Direccion")
                        .HasColumnType("text")
                        .HasColumnName("direccion");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("Activo")
                        .HasColumnName("estado");

                    b.Property<Guid?>("EtapaId")
                        .HasColumnType("uuid")
                        .HasColumnName("etapa_id");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("nombre");

                    b.Property<string>("Notas")
                        .HasColumnType("text")
                        .HasColumnName("notas");

                    b.Property<Guid?>("PaisId")
                        .HasColumnType("uuid")
                        .HasColumnName("pais_id");

                    b.Property<Guid?>("RegionId")
                        .HasColumnType("uuid")
                        .HasColumnName("region_id");

                    b.Property<string>("Sector")
                        .HasColumnType("text")
                        .HasColumnName("sector");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.Property<string>("ValorReferencia")
                        .HasColumnType("text")
                        .HasColumnName("valor_referencia");

                    b.Property<string>("Web")
                        .HasColumnType("text")
                        .HasColumnName("web");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_clientes");

                    b.HasIndex("Ciudad")
                        .HasDatabaseName("ix_clientes_ciudad");

                    b.HasIndex("CiudadId")
                        .HasDatabaseName("ix_clientes_ciudad_id");

                    b.HasIndex("CreatedBy")
                        .HasDatabaseName("ix_clientes_created_by");

                    b.HasIndex("Estado")
                        .HasDatabaseName("ix_clientes_estado");

                    b.HasIndex("EtapaId")
                        .HasDatabaseName("ix_clientes_etapa_id");

                    b.HasIndex("Nombre")
                        .HasDatabaseName("ix_clientes_nombre");

                    b.HasIndex("PaisId")
                        .HasDatabaseName("ix_clientes_pais_id");

                    b.HasIndex("RegionId")
                        .HasDatabaseName("ix_clientes_region_id");

                    b.ToTable("clientes", null, t =>
                        {
                            t.HasCheckConstraint("ck_clientes_estado", "estado IN ('Activo', 'Prospecto', 'Inactivo')");
                        });
                });

            modelBuilder.Entity("Nexit.Core.Entities.ClienteAdjunto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("ClienteId")
                        .HasColumnType("uuid")
                        .HasColumnName("cliente_id");

                    b.Property<string>("ContentType")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("content_type");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime>("Fecha")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha")
                        .HasDefaultValueSql("CURRENT_DATE");

                    b.Property<string>("Meta")
                        .HasColumnType("text")
                        .HasColumnName("meta");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("nombre");

                    b.Property<string>("StoragePath")
                        .HasColumnType("text")
                        .HasColumnName("storage_path");

                    b.Property<long?>("TamanoBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("tamano_bytes");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("tipo");

                    b.Property<string>("Url")
                        .HasColumnType("text")
                        .HasColumnName("url");

                    b.HasKey("Id")
                        .HasName("pk_cliente_adjuntos");

                    b.HasIndex("ClienteId")
                        .HasDatabaseName("ix_cliente_adjuntos_cliente_id");

                    b.ToTable("cliente_adjuntos", null, t =>
                        {
                            t.HasCheckConstraint("ck_cliente_adjuntos_tipo", "tipo IN ('link', 'file')");
                        });
                });

            modelBuilder.Entity("Nexit.Core.Entities.ClienteEmail", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("ClienteId")
                        .HasColumnType("uuid")
                        .HasColumnName("cliente_id");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<string>("Etiqueta")
                        .HasColumnType("text")
                        .HasColumnName("etiqueta");

                    b.HasKey("Id")
                        .HasName("pk_cliente_emails");

                    b.HasIndex("ClienteId")
                        .HasDatabaseName("ix_cliente_emails_cliente_id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_cliente_emails_email");

                    b.ToTable("cliente_emails", (string)null);
                });

            modelBuilder.Entity("Nexit.Core.Entities.ClienteTelefono", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("ClienteId")
                        .HasColumnType("uuid")
                        .HasColumnName("cliente_id");

                    b.Property<string>("Etiqueta")
                        .HasColumnType("text")
                        .HasColumnName("etiqueta");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("telefono");

                    b.HasKey("Id")
                        .HasName("pk_cliente_telefonos");

                    b.HasIndex("ClienteId")
                        .HasDatabaseName("ix_cliente_telefonos_cliente_id");

                    b.ToTable("cliente_telefonos", (string)null);
                });

            modelBuilder.Entity("Nexit.Core.Entities.DominioCorreoPermitido", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Dominio")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("dominio");

                    b.HasKey("Id")
                        .HasName("pk_dominios_correo_permitidos");

                    b.HasIndex("Dominio")
                        .IsUnique()
                        .HasDatabaseName("ix_dominios_correo_permitidos_dominio");

                    b.ToTable("dominios_correo_permitidos", (string)null);
                });

            modelBuilder.Entity("Nexit.Core.Entities.EstadoProyecto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<short>("Fase")
                        .HasColumnType("smallint")
                        .HasColumnName("fase");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("nombre");

                    b.Property<short>("Orden")
                        .HasColumnType("smallint")
                        .HasColumnName("orden");

                    b.HasKey("Id")
                        .HasName("pk_estados_proyecto");

                    b.HasIndex("Fase")
                        .HasDatabaseName("ix_estados_proyecto_fase");

                    b.HasIndex("Nombre")
                        .IsUnique()
                        .HasDatabaseName("ix_estados_proyecto_nombre");

                    b.HasIndex("Orden")
                        .IsUnique()
                        .HasDatabaseName("ix_estados_proyecto_orden");

                    b.ToTable("estados_proyecto", (string)null);
                });

            modelBuilder.Entity("Nexit.Core.Entities.EtapaCliente", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("nombre");

                    b.Property<short>("Orden")
                        .HasColumnType("smallint")
                        .HasColumnName("orden");

                    b.Property<short>("PorcentajeProceso")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)0)
                        .HasColumnName("porcentaje_proceso");

                    b.HasKey("Id")
                        .HasName("pk_etapas_cliente");

                    b.HasIndex("Nombre")
                        .IsUnique()
                        .HasDatabaseName("ix_etapas_cliente_nombre");

                    b.HasIndex("Orden")
                        .IsUnique()
                        .HasDatabaseName("ix_etapas_cliente_orden");

                    b.ToTable("etapas_cliente", null, t =>
                        {
                            t.HasCheckConstraint("ck_etapas_cliente_porcentaje", "porcentaje_proceso BETWEEN 0 AND 100");
                        });
                });

            modelBuilder.Entity("Nexit.Core.Entities.FaseProyecto", b =>
                {
                    b.Property<short>("Fase")
                        .HasColumnType("smallint")
                        .HasColumnName("fase");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("nombre");

                    b.HasKey("Fase")
                        .HasName("pk_fases_proyecto");

                    b.HasIndex("Nombre")
                        .IsUnique()
                        .HasDatabaseName("ix_fases_proyecto_nombre");

                    b.ToTable("fases_proyecto", (string)null);
                });

            modelBuilder.Entity("Nexit.Core.Entities.HistorialCambio", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Accion")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("accion");

                    b.Property<string>("Campo")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("campo");

                    b.Property<Guid>("EntidadId")
                        .HasColumnType("uuid")
                        .HasColumnName("entidad_id");

                    b.Property<DateTime>("Fecha")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("TipoEntidad")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("tipo_entidad");

                    b.Property<Guid?>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.Property<string>("ValorAnterior")
                        .HasColumnType("text")
                        .HasColumnName("valor_anterior");

                    b.Property<string>("ValorNuevo")
                        .HasColumnType("text")
                        .HasColumnName("valor_nuevo");

                    b.HasKey("Id")
                        .HasName("pk_historial_cambios");

                    b.HasIndex("UsuarioId")
                        .HasDatabaseName("ix_historial_cambios_usuario_id");

                    b.HasIndex("TipoEntidad", "EntidadId", "Fecha")
                        .HasDatabaseName("ix_historial_cambios_tipo_entidad_entidad_id_fecha");

                    b.ToTable("historial_cambios", null, t =>
                        {
                            t.HasCheckConstraint("ck_historial_cambios_tipo_entidad", "tipo_entidad IN ('proyecto', 'proveedor', 'cliente')");
                        });
                });

            modelBuilder.Entity("Nexit.Core.Entities.InformeSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("PeriodoKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("periodo_key");

                    b.Property<string>("PorBrief")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("por_brief");

                    b.Property<string>("PorEstado")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("por_estado");

                    b.Property<int>("ProyectosSinProveedor")
                        .HasColumnType("integer")
                        .HasColumnName("proyectos_sin_proveedor");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tipo");

                    b.Property<int>("TotalClientes")
                        .HasColumnType("integer")
                        .HasColumnName("total_clientes");

                    b.Property<int>("TotalProveedores")
                        .HasColumnType("integer")
                        .HasColumnName("total_proveedores");

                    b.Property<int>("TotalProyectos")
                        .HasColumnType("integer")
                        .HasColumnName("total_proyectos");

                    b.HasKey("Id")
                        .HasName("pk_informes_snapshot");

                    b.HasIndex("CreatedBy")
                        .HasDatabaseName("ix_informes_snapshot_created_by");

                    b.HasIndex("Tipo", "PeriodoKey")
                        .IsUnique()
                        .HasDatabaseName("ix_informes_snapshot_tipo_periodo_key");

                    b.ToTable("informes_snapshot", null, t =>
                        {
                            t.HasCheckConstraint("ck_informes_snapshot_tipo", "tipo IN ('semanal', 'mensual')");
                        });
                });

            modelBuilder.Entity("Nexit.Core.Entities.InvitacionEquipo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("estado");

                    b.Property<DateTime?>("FechaRespuesta")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_respuesta");

                    b.Property<Guid?>("InvitadoPorId")
                        .HasColumnType("uuid")
                        .HasColumnName("invitado_por_id");

                    b.Property<string>("Mensaje")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("mensaje");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("rol");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_invitaciones_equipo");

                    b.HasIndex("InvitadoPorId")
                        .HasDatabaseName("ix_invitaciones_equipo_invitado_por_id");

                    b.HasIndex("Email", "Estado")
                        .HasDatabaseName("ix_invitaciones_equipo_email_estado");

                    b.ToTable("invitaciones_equipo", null, t =>
                        {
                            t.HasCheckConstraint("ck_invitaciones_equipo_estado", "estado IN ('Pendiente', 'Aceptada', 'Rechazada')");
                        });
                });

            modelBuilder.Entity("Nexit.Core.Entities.Notificacion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid?>("EntidadId")
                        .HasColumnType("uuid")
                        .HasColumnName("entidad_id");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_creacion")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime?>("FechaLeida")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_leida");

                    b.Property<bool>("Leida")
                        .HasColumnType("boolean")
                        .HasColumnName("leida");

                    b.Property<string>("Mensaje")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("mensaje");

                    b.Property<Guid?>("SolicitudId")
                        .HasColumnType("uuid")
                        .HasColumnName("solicitud_id");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("tipo");

                    b.Property<string>("TipoEntidad")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("tipo_entidad");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("titulo");

                    b.Property<Guid>("UsuarioDestinatarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_destinatario_id");

                    b.HasKey("Id")
                        .HasName("pk_notificaciones");

                    b.HasIndex("UsuarioDestinatarioId", "Leida")
                        .HasDatabaseName("ix_notificaciones_usuario_destinatario_id_leida");

                    b.ToTable("notificaciones", null, t =>
                        {
                            t.HasCheckConstraint("ck_notificaciones_tipo", "tipo IN ('solicitud_eliminacion_creada', 'solicitud_eliminacion_endosada', 'solicitud_eliminacion_decidida', 'invitacion_aceptada', 'invitacion_rechazada')");
                        });
                });

            modelBuilder.Entity("Nexit.Core.Entities.Pais", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("EtiquetaRegion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("etiqueta_region");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("nombre");

                    b.HasKey("Id")
                        .HasName("pk_paises");

                    b.HasIndex("Nombre")
                        .IsUnique()
                        .HasDatabaseName("ix_paises_nombre");

                    b.ToTable("paises", (string)null);
                });

            modelBuilder.Entity("Nexit.Core.Entities.Proveedor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<int?>("Aforo")
                        .HasColumnType("integer")
                        .HasColumnName("aforo");

                    b.Property<string>("CargoContacto")
                        .HasColumnType("text")
                        .HasColumnName("cargo_contacto");

                    b.Property<Guid>("CategoriaId")
                        .HasColumnType("uuid")
                        .HasColumnName("categoria_id");

                    b.Property<Guid?>("CiudadId")
                        .HasColumnType("uuid")
                        .HasColumnName("ciudad_id");

                    b.Property<string>("Cobertura")
                        .HasColumnType("text")
                        .HasColumnName("cobertura");

                    b.Property<string>("Contacto")
                        .HasColumnType("text")
                        .HasColumnName("contacto");

                    b.Property<string>("CostoReferencia")
                        .HasColumnType("text")
                        .HasColumnName("costo_referencia");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("Direccion")
                        .HasColumnType("text")
                        .HasColumnName("direccion");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("Activo")
                        .HasColumnName("estado");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("nombre");

                    b.Property<string>("Notas")
                        .HasColumnType("text")
                        .HasColumnName("notas");

                    b.Property<Guid>("PaisId")
                        .HasColumnType("uuid")
                        .HasColumnName("pais_id");

                    b.Property<string>("Presupuesto")
                        .HasColumnType("text")
                        .HasColumnName("presupuesto");

                    b.Property<Guid?>("RegionId")
                        .HasColumnType("uuid")
                        .HasColumnName("region_id");

                    b.Property<int?>("Score")
                        .HasColumnType("integer")
                        .HasColumnName("score");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.Property<string>("Web")
                        .HasColumnType("text")
                        .HasColumnName("web");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_proveedores");

                    b.HasIndex("CategoriaId")
                        .HasDatabaseName("ix_proveedores_categoria_id");

                    b.HasIndex("CiudadId")
                        .HasDatabaseName("ix_proveedores_ciudad_id");

                    b.HasIndex("CreatedBy")
                        .HasDatabaseName("ix_proveedores_created_by");

                    b.HasIndex("Estado")
                        .HasDatabaseName("ix_proveedores_estado");

                    b.HasIndex("PaisId")
                        .HasDatabaseName("ix_proveedores_pais_id");

                    b.HasIndex("RegionId")
                        .HasDatabaseName("ix_proveedores_region_id");

                    b.ToTable("proveedores", null, t =>
                        {
                            t.HasCheckConstraint("ck_proveedores_cobertura", "cobertura IS NULL OR cobertura IN ('Solo ciudad', 'Regional', 'Nacional', 'Internacional')");

                            t.HasCheckConstraint("ck_proveedores_estado", "estado IN ('Activo', 'En evaluación', 'Pausado', 'Bloqueado')");

                            t.HasCheckConstraint("ck_proveedores_presupuesto", "presupuesto IS NULL OR presupuesto IN ('$ Bajo (<20k)', '$$ Medio (20k–100k)', '$$$ Alto (100k–500k)', '$$$$ Premium (>500k)')");

                            t.HasCheckConstraint("ck_proveedores_score", "score IS NULL OR score BETWEEN 1 AND 5");
                        });
                });

            modelBuilder.Entity("Nexit.Core.Entities.ProveedorAdjunto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("ContentType")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("content_type");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime>("Fecha")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha")
                        .HasDefaultValueSql("CURRENT_DATE");

                    b.Property<string>("Meta")
                        .HasColumnType("text")
                        .HasColumnName("meta");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("nombre");

                    b.Property<Guid>("ProveedorId")
                        .HasColumnType("uuid")
                        .HasColumnName("proveedor_id");

                    b.Property<string>("StoragePath")
                        .HasColumnType("text")
                        .HasColumnName("storage_path");

                    b.Property<long?>("TamanoBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("tamano_bytes");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("tipo");

                    b.Property<string>("Url")
                        .HasColumnType("text")
                        .HasColumnName("url");

                    b.HasKey("Id")
                        .HasName("pk_proveedor_adjuntos");

                    b.HasIndex("ProveedorId")
                        .HasDatabaseName("ix_proveedor_adjuntos_proveedor_id");

                    b.ToTable("proveedor_adjuntos", null, t =>
                        {
                            t.HasCheckConstraint("ck_proveedor_adjuntos_tipo", "tipo IN ('link', 'file')");
                        });
                });

            modelBuilder.Entity("Nexit.Core.Entities.ProveedorColaborador", b =>
                {
                    b.Property<Guid>("ProveedorId")
                        .HasColumnType("uuid")
                        .HasColumnName("proveedor_id");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.Property<DateTime>("FechaAgregado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_agregado")
                        .HasDefaultValueSql("now()");

                    b.HasKey("ProveedorId", "UsuarioId")
                        .HasName("pk_proveedor_colaboradores");

                    b.HasIndex("UsuarioId")
                        .HasDatabaseName("ix_proveedor_colaboradores_usuario_id");

                    b.ToTable("proveedor_colaboradores", (string)null);
                });

            modelBuilder.Entity("Nexit.Core.Entities.ProveedorEmail", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<string>("Etiqueta")
                        .HasColumnType("text")
                        .HasColumnName("etiqueta");

                    b.Property<Guid>("ProveedorId")
                        .HasColumnType("uuid")
                        .HasColumnName("proveedor_id");

                    b.HasKey("Id")
                        .HasName("pk_proveedor_emails");

                    b.HasIndex("ProveedorId")
                        .HasDatabaseName("ix_proveedor_emails_proveedor_id");

                    b.ToTable("proveedor_emails", (string)null);
                });

            modelBuilder.Entity("Nexit.Core.Entities.ProveedorServicio", b =>
                {
                    b.Property<Guid>("ProveedorId")
                        .HasColumnType("uuid")
                        .HasColumnName("proveedor_id");

                    b.Property<Guid>("ServicioId")
                        .HasColumnType("uuid")
                        .HasColumnName("servicio_id");

                    b.HasKey("ProveedorId", "ServicioId")
                        .HasName("pk_proveedor_servicios");

                    b.HasIndex("ServicioId")
                        .HasDatabaseName("ix_proveedor_servicios_servicio_id");

                    b.ToTable("proveedor_servicios", (string)null);
                });

            modelBuilder.Entity("Nexit.Core.Entities.ProveedorTelefono", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Etiqueta")
                        .HasColumnType("text")
                        .HasColumnName("etiqueta");

                    b.Property<Guid>("ProveedorId")
                        .HasColumnType("uuid")
                        .HasColumnName("proveedor_id");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("telefono");

                    b.HasKey("Id")
                        .HasName("pk_proveedor_telefonos");

                    b.HasIndex("ProveedorId")
                        .HasDatabaseName("ix_proveedor_telefonos_proveedor_id");

                    b.ToTable("proveedor_telefonos", (string)null);
                });

            modelBuilder.Entity("Nexit.Core.Entities.Proyecto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Ciudad")
                        .HasColumnType("text")
                        .HasColumnName("ciudad");

                    b.Property<Guid?>("ClienteId")
                        .HasColumnType("uuid")
                        .HasColumnName("cliente_id");

                    b.Property<string>("ContactoProyecto")
                        .HasColumnType("text")
                        .HasColumnName("contacto_proyecto");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("EstadoBrief")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("Pendiente por enviar")
                        .HasColumnName("estado_brief");

                    b.Property<Guid>("EstadoId")
                        .HasColumnType("uuid")
                        .HasColumnName("estado_id");

                    b.Property<DateTime?>("FechaEvento")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_evento");

                    b.Property<DateTime?>("FechaPago")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_pago");

                    b.Property<DateTime?>("FechaSolicitud")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_solicitud");

                    b.Property<Guid?>("GerenteId")
                        .HasColumnType("uuid")
                        .HasColumnName("gerente_id");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("nombre");

                    b.Property<string>("Notas")
                        .HasColumnType("text")
                        .HasColumnName("notas");

                    b.Property<string>("NumeroFactura")
                        .HasColumnType("text")
                        .HasColumnName("numero_factura");

                    b.Property<bool>("Pagado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("pagado");

                    b.Property<int>("PorcentajeAvance")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("porcentaje_avance");

                    b.Property<string>("Prioridad")
                        .HasColumnType("text")
                        .HasColumnName("prioridad");

                    b.Property<string>("PropuestaEstado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("No enviada")
                        .HasColumnName("propuesta_estado");

                    b.Property<string>("SedeNext")
                        .HasColumnType("text")
                        .HasColumnName("sede_next");

                    b.Property<string>("TipoProyecto")
                        .HasColumnType("text")
                        .HasColumnName("tipo_proyecto");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_proyectos");

                    b.HasIndex("ClienteId")
                        .HasDatabaseName("ix_proyectos_cliente_id");

                    b.HasIndex("CreatedBy")
                        .HasDatabaseName("ix_proyectos_created_by");

                    b.HasIndex("EstadoBrief")
                        .HasDatabaseName("ix_proyectos_estado_brief");

                    b.HasIndex("EstadoId")
                        .HasDatabaseName("ix_proyectos_estado_id");

                    b.HasIndex("FechaEvento")
                        .HasDatabaseName("ix_proyectos_fecha_evento");

                    b.HasIndex("GerenteId")
                        .HasDatabaseName("ix_proyectos_gerente_id");

                    b.HasIndex("Prioridad")
                        .HasDatabaseName("ix_proyectos_prioridad");

                    b.ToTable("proyectos", null, t =>
                        {
                            t.HasCheckConstraint("ck_proyectos_brief", "estado_brief IN ('Pendiente por enviar', 'Entregado, a espera de respuesta', 'Requiere ajustes', 'Aprobado')");

                            t.HasCheckConstraint("ck_proyectos_pago", "NOT pagado OR fecha_pago IS NOT NULL");

                            t.HasCheckConstraint("ck_proyectos_porcentaje", "porcentaje_avance BETWEEN 0 AND 100");

                            t.HasCheckConstraint("ck_proyectos_prioridad", "prioridad IS NULL OR prioridad IN ('Alta', 'Media', 'Baja')");

                            t.HasCheckConstraint("ck_proyectos_propuesta", "propuesta_estado IN ('No enviada', 'En proceso', 'Enviada')");

                            t.HasCheckConstraint("ck_proyectos_tipo", "tipo_proyecto IS NULL OR tipo_proyecto IN ('Corporativo', 'Evento social')");
                        });
                });

            modelBuilder.Entity("Nexit.Core.Entities.ProyectoAdjunto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("ContentType")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("content_type");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime>("Fecha")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha")
                        .HasDefaultValueSql("CURRENT_DATE");

                    b.Property<string>("Meta")
                        .HasColumnType("text")
                        .HasColumnName("meta");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("nombre");

                    b.Property<Guid>("ProyectoId")
                        .HasColumnType("uuid")
                        .HasColumnName("proyecto_id");

                    b.Property<string>("StoragePath")
                        .HasColumnType("text")
                        .HasColumnName("storage_path");

                    b.Property<long?>("TamanoBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("tamano_bytes");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("tipo");

                    b.Property<string>("Url")
                        .HasColumnType("text")
                        .HasColumnName("url");

                    b.HasKey("Id")
                        .HasName("pk_proyecto_adjuntos");

                    b.HasIndex("ProyectoId")
                        .HasDatabaseName("ix_proyecto_adjuntos_proyecto_id");

                    b.ToTable("proyecto_adjuntos", null, t =>
                        {
                            t.HasCheckConstraint("ck_proyecto_adjuntos_tipo", "tipo IN ('link', 'file')");
                        });
                });

            modelBuilder.Entity("Nexit.Core.Entities.ProyectoEquipo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre");

                    b.Property<Guid>("ProyectoId")
                        .HasColumnType("uuid")
                        .HasColumnName("proyecto_id");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("rol");

                    b.HasKey("Id")
                        .HasName("pk_proyecto_equipo");

                    b.HasIndex("ProyectoId")
                        .HasDatabaseName("ix_proyecto_equipo_proyecto_id");

                    b.ToTable("proyecto_equipo", null, t =>
                        {
                            t.HasCheckConstraint("ck_proyecto_equipo_rol", "rol IN ('Ejecutivo', 'Comercial', 'Administrativo', 'Diseñador 3D', 'Diseñador gráfico')");
                        });
                });

            modelBuilder.Entity("Nexit.Core.Entities.ProyectoProveedor", b =>
                {
                    b.Property<Guid>("ProyectoId")
                        .HasColumnType("uuid")
                        .HasColumnName("proyecto_id");

                    b.Property<Guid>("ProveedorId")
                        .HasColumnType("uuid")
                        .HasColumnName("proveedor_id");

                    b.HasKey("ProyectoId", "ProveedorId")
                        .HasName("pk_proyecto_proveedores");

                    b.HasIndex("ProveedorId")
                        .HasDatabaseName("ix_proyecto_proveedores_proveedor_id");

                    b.ToTable("proyecto_proveedores", (string)null);
                });

            modelBuilder.Entity("Nexit.Core.Entities.ProyectoSeguimiento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Area")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("General")
                        .HasColumnName("area");

                    b.Property<Guid?>("AutorId")
                        .HasColumnType("uuid")
                        .HasColumnName("autor_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime>("Fecha")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha")
                        .HasDefaultValueSql("CURRENT_DATE");

                    b.Property<string>("Nota")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nota");

                    b.Property<Guid>("ProyectoId")
                        .HasColumnType("uuid")
                        .HasColumnName("proyecto_id");

                    b.HasKey("Id")
                        .HasName("pk_proyecto_seguimiento");

                    b.HasIndex("AutorId")
                        .HasDatabaseName("ix_proyecto_seguimiento_autor_id");

                    b.HasIndex("ProyectoId")
                        .HasDatabaseName("ix_proyecto_seguimiento_proyecto_id");

                    b.ToTable("proyecto_seguimiento", null, t =>
                        {
                            t.HasCheckConstraint("ck_proyecto_seguimiento_area", "area IN ('General', 'Creativo', 'Comercial', 'Administrativo')");
                        });
                });

            modelBuilder.Entity("Nexit.Core.Entities.Region", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("nombre");

                    b.Property<Guid>("PaisId")
                        .HasColumnType("uuid")
                        .HasColumnName("pais_id");

                    b.HasKey("Id")
                        .HasName("pk_regiones");

                    b.HasIndex("PaisId", "Nombre")
                        .IsUnique()
                        .HasDatabaseName("ix_regiones_pais_id_nombre");

                    b.ToTable("regiones", (string)null);
                });

            modelBuilder.Entity("Nexit.Core.Entities.Servicio", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_servicios");

                    b.HasIndex("Nombre")
                        .IsUnique()
                        .HasDatabaseName("ix_servicios_nombre");

                    b.ToTable("servicios", (string)null);
                });

            modelBuilder.Entity("Nexit.Core.Entities.SolicitudEliminacion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime?>("AprobadoPorGerenteEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("aprobado_por_gerente_en");

                    b.Property<Guid?>("AprobadoPorGerenteId")
                        .HasColumnType("uuid")
                        .HasColumnName("aprobado_por_gerente_id");

                    b.Property<string>("ComentarioRevision")
                        .HasColumnType("text")
                        .HasColumnName("comentario_revision");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("EntidadId")
                        .HasColumnType("uuid")
                        .HasColumnName("entidad_id");

                    b.Property<string>("EntidadNombre")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("entidad_nombre");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("pendiente_admin")
                        .HasColumnName("estado");

                    b.Property<Guid?>("GerenteResponsableId")
                        .HasColumnType("uuid")
                        .HasColumnName("gerente_responsable_id");

                    b.Property<string>("Motivo")
                        .HasColumnType("text")
                        .HasColumnName("motivo");

                    b.Property<DateTime?>("RevisadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revisado_en");

                    b.Property<Guid?>("RevisadoPorId")
                        .HasColumnType("uuid")
                        .HasColumnName("revisado_por_id");

                    b.Property<Guid?>("SolicitadoPorId")
                        .HasColumnType("uuid")
                        .HasColumnName("solicitado_por_id");

                    b.Property<string>("TipoEntidad")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("tipo_entidad");

                    b.HasKey("Id")
                        .HasName("pk_solicitudes_eliminacion");

                    b.HasIndex("AprobadoPorGerenteId")
                        .HasDatabaseName("ix_solicitudes_eliminacion_aprobado_por_gerente_id");

                    b.HasIndex("Estado")
                        .HasDatabaseName("ix_solicitudes_eliminacion_estado");

                    b.HasIndex("GerenteResponsableId")
                        .HasDatabaseName("ix_solicitudes_eliminacion_gerente_responsable_id");

                    b.HasIndex("RevisadoPorId")
                        .HasDatabaseName("ix_solicitudes_eliminacion_revisado_por_id");

                    b.HasIndex("SolicitadoPorId")
                        .HasDatabaseName("ix_solicitudes_eliminacion_solicitado_por_id");

                    b.HasIndex("TipoEntidad", "EntidadId")
                        .HasDatabaseName("ix_solicitudes_eliminacion_tipo_entidad_entidad_id");

                    b.ToTable("solicitudes_eliminacion", null, t =>
                        {
                            t.HasCheckConstraint("ck_solicitudes_eliminacion_estado", "estado IN ('pendiente_gerente', 'pendiente_admin', 'aprobada', 'rechazada')");

                            t.HasCheckConstraint("ck_solicitudes_eliminacion_tipo", "tipo_entidad IN ('cliente', 'proveedor', 'proyecto', 'usuario')");
                        });
                });

            modelBuilder.Entity("Nexit.Core.Entities.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("activo");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("apellido");

                    b.Property<bool>("ContrasenaConfigurada")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("contrasena_configurada");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<DateTime?>("FechaDesactivacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_desactivacion");

                    b.Property<string>("Iniciales")
                        .HasColumnType("text")
                        .HasColumnName("iniciales");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("miembro")
                        .HasColumnName("rol");

                    b.Property<DateTime?>("UltimaActividad")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ultima_actividad");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("pk_usuarios");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_usuarios_email");

                    b.ToTable("usuarios", null, t =>
                        {
                            t.HasCheckConstraint("ck_usuarios_rol", "rol IN ('super_admin', 'admin', 'manager', 'miembro')");
                        });
                });

            modelBuilder.Entity("Nexit.Core.Entities.UsuarioEliminado", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("apellido");

                    b.Property<Guid?>("EliminadoPorId")
                        .HasColumnType("uuid")
                        .HasColumnName("eliminado_por_id");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<DateTime>("FechaAltaOriginal")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_alta_original");

                    b.Property<DateTime?>("FechaDesactivacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_desactivacion");

                    b.Property<DateTime>("FechaEliminacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_eliminacion")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Iniciales")
                        .HasColumnType("text")
                        .HasColumnName("iniciales");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("nombre");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("rol");

                    b.Property<Guid>("UsuarioIdOriginal")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id_original");

                    b.HasKey("Id")
                        .HasName("pk_usuarios_eliminados");

                    b.HasIndex("UsuarioIdOriginal")
                        .HasDatabaseName("ix_usuarios_eliminados_usuario_id_original");

                    b.ToTable("usuarios_eliminados", (string)null);
                });

            modelBuilder.Entity("Nexit.Core.Entities.Ciudad", b =>
                {
                    b.HasOne("Nexit.Core.Entities.Region", "Region")
                        .WithMany("Ciudades")
                        .HasForeignKey("RegionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_ciudades_regiones_region_id");

                    b.Navigation("Region");
                });

            modelBuilder.Entity("Nexit.Core.Entities.Cliente", b =>
                {
                    b.HasOne("Nexit.Core.Entities.Ciudad", null)
                        .WithMany()
                        .HasForeignKey("CiudadId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_clientes_ciudades_ciudad_id");

                    b.HasOne("Nexit.Core.Entities.Usuario", null)
                        .WithMany("ClientesCreados")
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_clientes_usuarios_created_by");

                    b.HasOne("Nexit.Core.Entities.EtapaCliente", null)
                        .WithMany()
                        .HasForeignKey("EtapaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_clientes_etapas_cliente_etapa_id");

                    b.HasOne("Nexit.Core.Entities.Pais", null)
                        .WithMany()
                        .HasForeignKey("PaisId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_clientes_paises_pais_id");

                    b.HasOne("Nexit.Core.Entities.Region", null)
                        .WithMany()
                        .HasForeignKey("RegionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_clientes_regiones_region_id");
                });

            modelBuilder.Entity("Nexit.Core.Entities.ClienteAdjunto", b =>
                {
                    b.HasOne("Nexit.Core.Entities.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_cliente_adjuntos_clientes_cliente_id");

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("Nexit.Core.Entities.ClienteEmail", b =>
                {
                    b.HasOne("Nexit.Core.Entities.Cliente", "Cliente")
                        .WithMany("Emails")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_cliente_emails_clientes_cliente_id");

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("Nexit.Core.Entities.ClienteTelefono", b =>
                {
                    b.HasOne("Nexit.Core.Entities.Cliente", "Cliente")
                        .WithMany("Telefonos")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_cliente_telefonos_clientes_cliente_id");

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("Nexit.Core.Entities.EstadoProyecto", b =>
                {
                    b.HasOne("Nexit.Core.Entities.FaseProyecto", "FaseProyecto")
                        .WithMany("Estados")
                        .HasForeignKey("Fase")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_estados_proyecto_fases_proyecto_fase");

                    b.Navigation("FaseProyecto");
                });

            modelBuilder.Entity("Nexit.Core.Entities.HistorialCambio", b =>
                {
                    b.HasOne("Nexit.Core.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_historial_cambios_usuarios_usuario_id");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Nexit.Core.Entities.InformeSnapshot", b =>
                {
                    b.HasOne("Nexit.Core.Entities.Usuario", null)
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_informes_snapshot_usuarios_created_by");
                });

            modelBuilder.Entity("Nexit.Core.Entities.InvitacionEquipo", b =>
                {
                    b.HasOne("Nexit.Core.Entities.Usuario", "InvitadoPor")
                        .WithMany()
                        .HasForeignKey("InvitadoPorId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_invitaciones_equipo_usuarios_invitado_por_id");

                    b.Navigation("InvitadoPor");
                });

            modelBuilder.Entity("Nexit.Core.Entities.Notificacion", b =>
                {
                    b.HasOne("Nexit.Core.Entities.Usuario", "UsuarioDestinatario")
                        .WithMany()
                        .HasForeignKey("UsuarioDestinatarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_notificaciones_usuarios_usuario_destinatario_id");

                    b.Navigation("UsuarioDestinatario");
                });

            modelBuilder.Entity("Nexit.Core.Entities.Proveedor", b =>
                {
                    b.HasOne("Nexit.Core.Entities.CategoriaProveedor", null)
                        .WithMany()
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_proveedores_categorias_proveedor_categoria_id");

                    b.HasOne("Nexit.Core.Entities.Ciudad", null)
                        .WithMany()
                        .HasForeignKey("CiudadId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_proveedores_ciudades_ciudad_id");

                    b.HasOne("Nexit.Core.Entities.Usuario", null)
                        .WithMany("ProveedoresCreados")
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_proveedores_usuarios_created_by");

                    b.HasOne("Nexit.Core.Entities.Pais", null)
                        .WithMany()
                        .HasForeignKey("PaisId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_proveedores_paises_pais_id");

                    b.HasOne("Nexit.Core.Entities.Region", null)
                        .WithMany()
                        .HasForeignKey("RegionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_proveedores_regiones_region_id");
                });

            modelBuilder.Entity("Nexit.Core.Entities.ProveedorAdjunto", b =>
                {
                    b.HasOne("Nexit.Core.Entities.Proveedor", "Proveedor")
                        .WithMany("Adjuntos")
                        .HasForeignKey("ProveedorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_proveedor_adjuntos_proveedores_proveedor_id");

                    b.Navigation("Proveedor");
                });

            modelBuilder.Entity("Nexit.Core.Entities.ProveedorColaborador", b =>
                {
                    b.HasOne("Nexit.Core.Entities.Proveedor", "Proveedor")
                        .WithMany("Colaboradores")
                        .HasForeignKey("ProveedorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_proveedor_colaboradores_proveedores_proveedor_id");

                    b.HasOne("Nexit.Core.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_proveedor_colaboradores_usuarios_usuario_id");

                    b.Navigation("Proveedor");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Nexit.Core.Entities.ProveedorEmail", b =>
                {
                    b.HasOne("Nexit.Core.Entities.Proveedor", "Proveedor")
                        .WithMany("Emails")
                        .HasForeignKey("ProveedorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_proveedor_emails_proveedores_proveedor_id");

                    b.Navigation("Proveedor");
                });

            modelBuilder.Entity("Nexit.Core.Entities.ProveedorServicio", b =>
                {
                    b.HasOne("Nexit.Core.Entities.Proveedor", "Proveedor")
                        .WithMany("Servicios")
                        .HasForeignKey("ProveedorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_proveedor_servicios_proveedores_proveedor_id");

                    b.HasOne("Nexit.Core.Entities.Servicio", "Servicio")
                        .WithMany("Proveedores")
                        .HasForeignKey("ServicioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_proveedor_servicios_servicios_servicio_id");

                    b.Navigation("Proveedor");

                    b.Navigation("Servicio");
                });

            modelBuilder.Entity("Nexit.Core.Entities.ProveedorTelefono", b =>
                {
                    b.HasOne("Nexit.Core.Entities.Proveedor", "Proveedor")
                        .WithMany("Telefonos")
                        .HasForeignKey("ProveedorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_proveedor_telefonos_proveedores_proveedor_id");

                    b.Navigation("Proveedor");
                });

            modelBuilder.Entity("Nexit.Core.Entities.Proyecto", b =>
                {
                    b.HasOne("Nexit.Core.Entities.Cliente", "Cliente")
                        .WithMany("Proyectos")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_proyectos_clientes_cliente_id");

                    b.HasOne("Nexit.Core.Entities.Usuario", null)
                        .WithMany("ProyectosCreados")
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_proyectos_usuarios_created_by");

                    b.HasOne("Nexit.Core.Entities.EstadoProyecto", null)
                        .WithMany()
                        .HasForeignKey("EstadoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_proyectos_estados_proyecto_estado_id");

                    b.HasOne("Nexit.Core.Entities.Usuario", "Gerente")
                        .WithMany()
                        .HasForeignKey("GerenteId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_proyectos_usuarios_gerente_id");

                    b.Navigation("Cliente");

                    b.Navigation("Gerente");
                });

            modelBuilder.Entity("Nexit.Core.Entities.ProyectoAdjunto", b =>
                {
                    b.HasOne("Nexit.Core.Entities.Proyecto", "Proyecto")
                        .WithMany()
                        .HasForeignKey("ProyectoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_proyecto_adjuntos_proyectos_proyecto_id");

                    b.Navigation("Proyecto");
                });

            modelBuilder.Entity("Nexit.Core.Entities.ProyectoEquipo", b =>
                {
                    b.HasOne("Nexit.Core.Entities.Proyecto", "Proyecto")
                        .WithMany("Equipo")
                        .HasForeignKey("ProyectoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_proyecto_equipo_proyectos_proyecto_id");

                    b.Navigation("Proyecto");
                });

            modelBuilder.Entity("Nexit.Core.Entities.ProyectoProveedor", b =>
                {
                    b.HasOne("Nexit.Core.Entities.Proveedor", "Proveedor")
                        .WithMany("Proyectos")
                        .HasForeignKey("ProveedorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_proyecto_proveedores_proveedores_proveedor_id");

                    b.HasOne("Nexit.Core.Entities.Proyecto", "Proyecto")
                        .WithMany("Proveedores")
                        .HasForeignKey("ProyectoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_proyecto_proveedores_proyectos_proyecto_id");

                    b.Navigation("Proveedor");

                    b.Navigation("Proyecto");
                });

            modelBuilder.Entity("Nexit.Core.Entities.ProyectoSeguimiento", b =>
                {
                    b.HasOne("Nexit.Core.Entities.Usuario", "Autor")
                        .WithMany("SeguimientosEscritos")
                        .HasForeignKey("AutorId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_proyecto_seguimiento_usuarios_autor_id");

                    b.HasOne("Nexit.Core.Entities.Proyecto", "Proyecto")
                        .WithMany("Seguimiento")
                        .HasForeignKey("ProyectoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_proyecto_seguimiento_proyectos_proyecto_id");

                    b.Navigation("Autor");

                    b.Navigation("Proyecto");
                });

            modelBuilder.Entity("Nexit.Core.Entities.Region", b =>
                {
                    b.HasOne("Nexit.Core.Entities.Pais", "Pais")
                        .WithMany("Regiones")
                        .HasForeignKey("PaisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_regiones_paises_pais_id");

                    b.Navigation("Pais");
                });

            modelBuilder.Entity("Nexit.Core.Entities.SolicitudEliminacion", b =>
                {
                    b.HasOne("Nexit.Core.Entities.Usuario", "AprobadoPorGerente")
                        .WithMany()
                        .HasForeignKey("AprobadoPorGerenteId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_solicitudes_eliminacion_usuarios_aprobado_por_gerente_id");

                    b.HasOne("Nexit.Core.Entities.Usuario", "GerenteResponsable")
                        .WithMany()
                        .HasForeignKey("GerenteResponsableId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_solicitudes_eliminacion_usuarios_gerente_responsable_id");

                    b.HasOne("Nexit.Core.Entities.Usuario", "RevisadoPor")
                        .WithMany()
                        .HasForeignKey("RevisadoPorId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_solicitudes_eliminacion_usuarios_revisado_por_id");

                    b.HasOne("Nexit.Core.Entities.Usuario", "SolicitadoPor")
                        .WithMany()
                        .HasForeignKey("SolicitadoPorId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_solicitudes_eliminacion_usuarios_solicitado_por_id");

                    b.Navigation("AprobadoPorGerente");

                    b.Navigation("GerenteResponsable");

                    b.Navigation("RevisadoPor");

                    b.Navigation("SolicitadoPor");
                });

            modelBuilder.Entity("Nexit.Core.Entities.Cliente", b =>
                {
                    b.Navigation("Emails");

                    b.Navigation("Proyectos");

                    b.Navigation("Telefonos");
                });

            modelBuilder.Entity("Nexit.Core.Entities.FaseProyecto", b =>
                {
                    b.Navigation("Estados");
                });

            modelBuilder.Entity("Nexit.Core.Entities.Pais", b =>
                {
                    b.Navigation("Regiones");
                });

            modelBuilder.Entity("Nexit.Core.Entities.Proveedor", b =>
                {
                    b.Navigation("Adjuntos");

                    b.Navigation("Colaboradores");

                    b.Navigation("Emails");

                    b.Navigation("Proyectos");

                    b.Navigation("Servicios");

                    b.Navigation("Telefonos");
                });

            modelBuilder.Entity("Nexit.Core.Entities.Proyecto", b =>
                {
                    b.Navigation("Equipo");

                    b.Navigation("Proveedores");

                    b.Navigation("Seguimiento");
                });

            modelBuilder.Entity("Nexit.Core.Entities.Region", b =>
                {
                    b.Navigation("Ciudades");
                });

            modelBuilder.Entity("Nexit.Core.Entities.Servicio", b =>
                {
                    b.Navigation("Proveedores");
                });

            modelBuilder.Entity("Nexit.Core.Entities.Usuario", b =>
                {
                    b.Navigation("ClientesCreados");

                    b.Navigation("ProveedoresCreados");

                    b.Navigation("ProyectosCreados");

                    b.Navigation("SeguimientosEscritos");
                });
#pragma warning restore 612, 618
        }
    }
}
